In [22]:
import pandas as pd
dtset = pd.read_csv("Placement.csv")
dtset = dtset.drop(columns=['sl_no'])

# Quantitative columns
quan = dtset.select_dtypes(include=['number']).columns

# Qualitative columns
qual = dtset.select_dtypes(include=['object', 'category']).columns

quan

Index(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'], dtype='object')

In [23]:
qual

Index(['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex',
       'specialisation', 'status'],
      dtype='object')

In [24]:
men  = dtset["mba_p"].mean()
mdn = dtset["mba_p"].median()
mde = dtset["mba_p"].mode()[0]
trdmde = dtset["mba_p"].value_counts().index[2]
print("mean:", men)
print("median:", mdn)
print("mode:", mde)
print ("3rd mode", trdmde)

mean: 62.278186046511635
median: 62.0
mode: 56.7
3rd mode 64.15

In [13]:
dtset.describe()

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [87]:
destbl = pd.DataFrame()
destbl = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule", "Lessor", "Greater","Min","Max","LrOutlier", "GtrOutlier"], columns = quan)
for colName in quan:
    destbl.loc["Mean", colName] = dtset[colName].mean()
    destbl.loc["Median", colName] = dtset[colName].median()
    destbl.loc["Mode", colName] = dtset[colName].mode()[0]
    destbl.loc["Q1:25%", colName] = dtset[colName].quantile(0.25)
    destbl.loc["Q2:50%", colName] = dtset[colName].quantile(0.50)
    destbl.loc["Q3:75%", colName] = dtset[colName].quantile(0.75)
    destbl.loc["99%", colName] = dtset[colName].quantile(0.99)
    destbl.loc["Q4:100%", colName] = dtset[colName].quantile(1.0)
    destbl.loc["IQR", colName] = dtset[colName].quantile(0.75) - dtset[colName].quantile(0.25)
    destbl.loc["1.5Rule", colName] = 1.5*destbl.loc["IQR", colName]

    lessor = dtset[colName].quantile(0.25) - (1.5*destbl.loc["IQR", colName])
    greater = dtset[colName].quantile(0.75) + (1.5*destbl.loc["IQR", colName])
    
    destbl.loc["Lessor", colName] = lessor
    destbl.loc["Greater", colName] = greater
    destbl.loc["Min", colName] = dtset[colName].min()
    destbl.loc["Max", colName] = dtset[colName].max()

    destbl.loc["LrOutlier", colName] = "Yes" if dtset[colName].min() < lessor else "No"
    destbl.loc["GtrOutlier", colName] = "Yes" if dtset[colName].max() > greater else "No"
    
destbl

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,75.7,73.0,72.0,83.5,66.255,300000.0
99%,87.0,91.86,83.86,97.0,76.1142,671200.0
Q4:100%,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,22.65,18.15,16.5,35.25,12.465,90000.0
Lessor,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,98.35,91.15,88.5,118.75,78.72,390000.0
Min,40.89,37.0,50.0,50.0,51.21,200000.0
Max,89.4,97.7,91.0,98.0,77.89,940000.0
LrOutlier,No,Yes,No,No,No,No
GtrOutlier,No,Yes,Yes,No,No,Yes

In [30]:
destbl = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule", "Lessor", "Greater","Min","Max","LrOutlier", "GtrOutlier","LrOutlier_Af","GtrOutlier_Af","Kurtosis", "Skewness"], columns = quan)
for colName in quan:
    destbl.loc["Mean", colName] = dtset[colName].mean()
    destbl.loc["Median", colName] = dtset[colName].median()
    destbl.loc["Mode", colName] = dtset[colName].mode()[0]
    destbl.loc["Q1:25%", colName] = dtset[colName].quantile(0.25)
    destbl.loc["Q2:50%", colName] = dtset[colName].quantile(0.50)
    destbl.loc["Q3:75%", colName] = dtset[colName].quantile(0.75)
    destbl.loc["99%", colName] = dtset[colName].quantile(0.99)
    destbl.loc["Q4:100%", colName] = dtset[colName].quantile(1.0)
    destbl.loc["IQR", colName] = dtset[colName].quantile(0.75) - dtset[colName].quantile(0.25)
    destbl.loc["1.5Rule", colName] = 1.5*destbl.loc["IQR", colName]

    lessor = dtset[colName].quantile(0.25) - (1.5*destbl.loc["IQR", colName])
    greater = dtset[colName].quantile(0.75) + (1.5*destbl.loc["IQR", colName])
    
    destbl.loc["Lessor", colName] = lessor
    destbl.loc["Greater", colName] = greater
    destbl.loc["Min", colName] = dtset[colName].min()
    destbl.loc["Max", colName] = dtset[colName].max()

    destbl.loc["LrOutlier", colName] = "Yes" if dtset[colName].min() < lessor else "No"

    destbl.loc["GtrOutlier", colName] = "Yes" if dtset[colName].max() > greater else "No"

    dtset.loc[dtset[colName] < lessor, colName] = lessor
    dtset.loc[dtset[colName] > greater, colName] = greater

    destbl.loc["LrOutlier_Af", colName] = "Yes" if dtset[colName].min() < lessor else "No"
    destbl.loc["GtrOutlier_Af", colName] = "Yes" if dtset[colName].max() > greater else "No"

    destbl.loc["Kurtosis", colName] = dtset[colName].kurtosis()
    destbl.loc["Skewness", colName] = dtset[colName].skew()

    
destbl

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,75.7,73.0,72.0,83.5,66.255,300000.0
99%,87.0,91.86,83.86,97.0,76.1142,671200.0
Q4:100%,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,22.65,18.15,16.5,35.25,12.465,90000.0
Lessor,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,98.35,91.15,88.5,118.75,78.72,390000.0
Min,40.89,37.0,50.0,50.0,51.21,200000.0
Max,89.4,97.7,91.0,98.0,77.89,940000.0
LrOutlier,No,Yes,No,No,No,No
GtrOutlier,No,Yes,Yes,No,No,Yes
LrOutlier_Af,No,No,No,No,No,No
GtrOutlier_Af,No,No,No,No,No,No
Kurtosis,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837
Skewness,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067

In [27]:
    def freqTable(dataset, columnName):
        freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])
        freqTable["Unique_Values"]=dataset[columnName].value_counts().sort_index()
        freqTable["Frequency"]=dataset[columnName].value_counts().values
        freqTable["Relative Frequency"]=freqTable["Frequency"]/dataset[columnName].value_counts().sort_index().sum()
        freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()
        return freqTable

In [28]:
fqtbl = freqTable(dtset,quan)
fqtbl

                                             Unique_Values  Frequency  \
ssc_p hsc_p degree_p etest_p mba_p salary
49.00 59.00 65.00    86.00   62.48 340000.0              1          1
52.60 65.58 72.11    57.60   56.66 265000.0              1          1
53.00 63.00 60.00    70.00   53.20 250000.0              1          1
55.68 61.33 56.87    66.00   58.30 260000.0              1          1
56.60 64.80 70.20    84.27   67.20 336000.0              1          1
...                                                    ...        ...
87.00 65.00 81.00    88.00   72.78 260000.0              1          1
      74.00 65.00    75.00   72.29 300000.0              1          1
      87.00 68.00    95.00   62.90 300000.0              1          1
88.00 72.00 78.00    82.00   71.43 252000.0              1          1
89.40 65.66 71.25    72.00   63.23 400000.0              1          1

                                             Relative Frequency     Cusum
ssc_p hsc_p degree_p etest_p mba_p salary
49.00 59.00 65.00    86.00   62.48 340000.0            0.006757  0.006757
52.60 65.58 72.11    57.60   56.66 265000.0            0.006757  0.013514
53.00 63.00 60.00    70.00   53.20 250000.0            0.006757  0.020270
55.68 61.33 56.87    66.00   58.30 260000.0            0.006757  0.027027
56.60 64.80 70.20    84.27   67.20 336000.0            0.006757  0.033784
...                                                         ...       ...
87.00 65.00 81.00    88.00   72.78 260000.0            0.006757  0.972973
      74.00 65.00    75.00   72.29 300000.0            0.006757  0.979730
      87.00 68.00    95.00   62.90 300000.0            0.006757  0.986486
88.00 72.00 78.00    82.00   71.43 252000.0            0.006757  0.993243
89.40 65.66 71.25    72.00   63.23 400000.0            0.006757  1.000000

[148 rows x 4 columns]